import classical_set_theory_functions_relations_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace classical_set_theory_functions_relations_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end classical_set_theory_functions_relations_theorem_canonical_lane_mathlib
end HautevilleHouse
